OPENAI_API_KEY = "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"
HUGGINGFACEHUB_API_TOKEN = "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"
EMAIL = "dholling4@gmail.com"
PASS = "John316316!!!"

[connections.pets_db]
url = "sqlite:///workspaces/PolarPlotter/pets.db"

[connections.pre_order_data.db]
url = "sqlite:///workspaces/PolarPlotter/database.db"

